config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :consulta
  resources :medicos

  resources :pacientes do
    resources :enderecos
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  validates :nome_completo, presence: true, length: {minimum: 4}, format: {with: /\A[^0-9`!@#$%^&*+_=,.]+\z/}
  validates :data_nascimento, presence: true, comparison: {less_than: Date.today, greater_than: Date.new(1850, 1, 1)}
  validates :CPF, presence: true, length: {is: 11}, format: {without: /\A[a-zA-Z]\z/}, uniqueness: true
  validates :email, presence: true, length: {minimum: 4}, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}

  has_one :endereco, dependent: :destroy
  has_many :consultums
  has_many :medicos, through: :consultums

  accepts_nested_attributes_for :endereco
  accepts_nested_attributes_for :consultums
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    @paciente.build_endereco
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes or /pacientes.json
  def create
    puts paciente_params
    puts endereco_params
    @paciente = Paciente.new(paciente_params)
    @paciente.build_endereco(endereco_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully created with Endereco." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1 or /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params) && @paciente.endereco.update(endereco_params)
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1 or /pacientes/1.json
  def destroy
    @paciente.destroy

    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def agendar_consulta
    @paciente = Paciente.find(params[:id])
    @consulta = @paciente.consultums.build(consultum_params)

    if @consulta.save
      redirect_to @paciente, notice: 'Consulta agendada com sucesso.'
    else
      render :show
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_paciente
    @paciente = Paciente.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def paciente_params
    params.require(:paciente).permit(:nome_completo, :data_nascimento, :CPF, :email)
  end

  def endereco_params
    params.require(:paciente).permit(:CEP, :cidade, :bairro, :logradouro, :complemento)
  end

  def consultum_params
    params.require(:consulta).permit(:data, :horario, :medico_id)
  end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome_completo, style: "display: block" %>
    <%= form.text_field :nome_completo %>
  </div>

  <div>
    <%= form.label :data_nascimento, style: "display: block" %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div>
    <%= form.label :CPF, style: "display: block" %>
    <%= form.text_field :CPF %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <h2>Endereco</h2>

    <div>
      <%= form.label :CEP, style: "display: block" %>
      <%= form.text_field :CEP %>
    </div>

    <div>
      <%= form.label :cidade, style: "display: block" %>
      <%= form.text_field :cidade %>
    </div>

    <div>
      <%= form.label :bairro, style: "display: block" %>
      <%= form.text_field :bairro %>
    </div>

    <div>
      <%= form.label :logradouro, style: "display: block" %>
      <%= form.text_field :logradouro %>
    </div>

    <div>
      <%= form.label :complemento, style: "display: block" %>
      <%= form.text_field :complemento %>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/_paciente.html.erb
<div id="<%= dom_id paciente %>">
  <p>
    <strong>Nome completo:</strong>
    <%= paciente.nome_completo %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= paciente.data_nascimento.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= paciente.CPF %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= paciente.email %>
  </p>

</div>

app/views/pacientes/edit.html.erb
<h1>Editing paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Show this paciente", @paciente %> |
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pacientes</h1>

<div id="pacientes">
  <% @pacientes.each do |paciente| %>
    <%= render paciente %>
    <p>
      <%= link_to "Show this paciente", paciente %>
    </p>
  <% end %>
</div>

<%= link_to "New paciente", new_paciente_path %>

<%= link_to "HomePage", root_path %>

app/views/pacientes/new.html.erb
<h1>New paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paciente %>

<div>
  <%= link_to "Edit this paciente", edit_paciente_path(@paciente) %> |
  <%= link_to "Back to pacientes", pacientes_path %>

  <%= button_to "Destroy this paciente", @paciente, method: :delete %>
</div>

<h2>Endereço</h2>
<% if @paciente.endereco %>
  <p><strong>CEP:</strong> <%= @paciente.endereco.CEP %></p>
  <p><strong>Cidade:</strong> <%= @paciente.endereco.cidade %></p>
  <p><strong>Bairro:</strong> <%= @paciente.endereco.bairro %></p>
  <p><strong>Logradouro:</strong> <%= @paciente.endereco.logradouro %></p>
  <p><strong>Complemento:</strong> <%= @paciente.endereco.complemento %></p>
<% else %>
  <p>O paciente não possui endereço cadastrado.</p>
<% end %>


<!-- Formulário para agendar consulta -->


<%= link_to "Agendar consulta", new_consultum_path %>

<%= link_to 'Back', pacientes_path %>