config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :consulta
  resources :medicos

  resources :pacientes do
    resources :enderecos
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/consulta_controller.rb
class ConsultaController < ApplicationController
  before_action :set_consultum, only: %i[ show edit update destroy ]

  # GET /consulta or /consulta.json
  def index
    @consulta = Consultum.all
  end

  # GET /consulta/1 or /consulta/1.json
  def show
  end

  # GET /consulta/new
  def new
    @consultum = Consultum.new
  end

  # GET /consulta/1/edit
  def edit
  end

  # POST /consulta or /consulta.json
  def create
    @consultum = Consultum.new(consultum_params)
    #@consultum.paciente = Paciente.find(paciente_params)

    respond_to do |format|
      if @consultum.save
        format.html { redirect_to consultum_url(@consultum), notice: "Consultum was successfully created." }
        format.json { render :show, status: :created, location: @consultum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consulta/1 or /consulta/1.json
  def update
    respond_to do |format|
      if @consultum.update(consultum_params)
        format.html { redirect_to consultum_url(@consultum), notice: "Consultum was successfully updated." }
        format.json { render :show, status: :ok, location: @consultum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consulta/1 or /consulta/1.json
  def destroy
    @consultum.destroy

    respond_to do |format|
      format.html { redirect_to consulta_url, notice: "Consultum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultum
      @consultum = Consultum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultum_params
      params.require(:consultum).permit(:paciente_id, :medico_id, :data, :horario)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/views/consulta/_consultum.html.erb
<div id="<%= dom_id consultum %>">
  <p>
    <strong>Paciente:</strong>
    <%= consultum.paciente.nome_completo %>
  </p>

  <p>
    <strong>Medico:</strong>
    <%= consultum.medico.nome_completo %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= consultum.data %>
  </p>

  <p>
    <strong>Horario:</strong>
    <%= consultum.horario %>
  </p>

</div>

app/views/consulta/_form.html.erb
<%= form_with(model: consultum) do |form| %>
  <% if consultum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(consultum.errors.count, "error") %> prohibited this consultum from being saved:</h2>

      <ul>
        <% consultum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :paciente_id, style: "display: block" %>
    <%= form.collection_select :paciente_id, Paciente.all, :id, :nome_completo %>
  </div>

  <div>
    <%= form.label :medico_id, style: "display: block" %>
    <%= form.collection_select :medico_id, Medico.all, :id, :nome_completo %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.time_field :horario %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/consulta/edit.html.erb
<h1>Editing consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Show this consultum", @consultum %> |
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Consulta</h1>

<div id="consulta">
  <% @consulta.each do |consultum| %>
    <%= render consultum %>
    <p>
      <%= link_to "Show this consultum", consultum %>
    </p>
  <% end %>
</div>

<%= link_to "New consultum", new_consultum_path %>

<%= link_to "HomePage", root_path %>

app/views/consulta/new.html.erb
<h1>New consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @consultum %>

<div>
  <%= link_to "Edit this consultum", edit_consultum_path(@consultum) %> |
  <%= link_to "Back to consulta", consulta_path %>

  <%= button_to "Destroy this consultum", @consultum, method: :delete %>
</div>