config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :consulta
  resources :medicos

  resources :pacientes do
    resources :enderecos
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/medico.rb
class Medico < ApplicationRecord
  validates :nome_completo, presence: true, length: {minimum: 5}, format: {with: /\A[^0-9`!@#$%^&*+_=,.]+\z/}
  validates :CPF, presence: true, length: {is: 11}, format: {without: /\A[a-zA-Z]\z/}, uniqueness: true
  validates :email, presence: true, length: {minimum: 5}, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}
  validates :especialidade, presence: true, length: {minimum: 5}, format: {with: /\A[^0-9`!@#$%^&*+_=]+\z/}
  validates :CRM, presence: true, length: {is: 6}, format: {without: /\A[a-zA-Z]\z/}

  has_many :consultums
  has_many :pacientes, :through => :consultums

  accepts_nested_attributes_for :consultums
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: %i[ show edit update destroy ]

  # GET /medicos or /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1 or /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos or /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully created." }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1 or /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully updated." }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1 or /medicos/1.json
  def destroy
    @medico.destroy

    respond_to do |format|
      format.html { redirect_to medicos_url, notice: "Medico was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medico_params
      params.require(:medico).permit(:nome_completo, :CPF, :email, :especialidade, :CRM)
    end
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/_form.html.erb
<%= form_with(model: medico) do |form| %>
  <% if medico.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
        <% medico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome_completo, style: "display: block" %>
    <%= form.text_field :nome_completo %>
  </div>

  <div>
    <%= form.label :CPF, style: "display: block" %>
    <%= form.text_field :CPF %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :especialidade, style: "display: block" %>
    <%= form.text_field :especialidade %>
  </div>

  <div>
    <%= form.label :CRM, style: "display: block" %>
    <%= form.text_field :CRM %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/_medico.html.erb
<div id="<%= dom_id medico %>">
  <p>
    <strong>Nome completo:</strong>
    <%= medico.nome_completo %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= medico.CPF %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= medico.email %>
  </p>

  <p>
    <strong>Especialidade:</strong>
    <%= medico.especialidade %>
  </p>

  <p>
    <strong>CRM:</strong>
    <%= medico.CRM %>
  </p>

</div>

app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Show this medico", @medico %> |
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Medicos</h1>

<div id="medicos">
  <% @medicos.each do |medico| %>
    <%= render medico %>
    <p>
      <%= link_to "Show this medico", medico %>
    </p>
  <% end %>
</div>

<%= link_to "New medico", new_medico_path %>

<%= link_to "HomePage", root_path %>

app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medico %>

<% if @medico.consultums.any? %>
  <h2>Consultas agendadas para <%= @medico.nome_completo %></h2>
  <ul>
    <% @medico.consultums.each do |consulta| %>
      <li>
        Data: <%= consulta.data %><br>
        Horário: <%= consulta.horario %><br>
        Paciente: <%= consulta.paciente.nome_completo %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Não há consultas agendadas para <%= @medico.nome_completo %>.</p>
<% end %>

<div>
  <%= link_to "Edit this medico", edit_medico_path(@medico) %> |
  <%= link_to "Back to medicos", medicos_path %>
  <%= button_to "Destroy this medico", @medico, method: :delete %>
</div>